# Stage 1: Build
FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

# Copy package.json and install dependencies
COPY package.json pnpm-lock.yaml* ./

RUN pnpm install

# Copy source files
COPY . .

CMD ["pnpm", "run", "dev"]

