# Stage 1: Build
FROM node:20-alpine

WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./

RUN npm install

# Copy source files
COPY . .

CMD ["npm", "run", "dev"]

